// src/components/layout/Navbar.jsx
import { useState, useEffect } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { ChevronDown, Menu, X } from 'lucide-react'
import logoKey from '../../assets/logoKey.png'

const products = [
  { label: 'Tarjetas PVC Bancarias', href: '/tarjetas-bancarias' },
  { label: 'Tarjetas Empresa', href: '/tarjetas-empresa' },
  { label: 'Fundas RFID', href: '/fundas-rfid' },
  { label: 'Rollos Térmicos', href: '/rollos-termicos' },
  { label: 'Sobres y Formularios', href: '/sobres-preimpresos' },
]

export default function Navbar() {
  const [scrolled, setScrolled] = useState(false)
  const [dropdownOpen, setDropdownOpen] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const { pathname } = useLocation()

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20)
    window.addEventListener('scroll', onScroll)
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  useEffect(() => {
    setMobileOpen(false)
    setDropdownOpen(false)
  }, [pathname])

  const navLink = 'text-sm font-medium transition-colors duration-200'
  const activeClass = 'text-brand-gold'
  const inactiveClass = 'text-gray-700 hover:text-brand-blue'

  return (
    <nav
      className={`sticky top-0 z-50 bg-white transition-shadow duration-300 ${
        scrolled ? 'shadow-md' : 'shadow-sm'
      }`}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 flex items-center justify-between h-16">
        {/* Logo */}
        <Link to="/" className="flex-shrink-0">
          <img src={logoKey} alt="Key Solutions" className="h-10 w-auto" />
        </Link>

        {/* Desktop nav */}
        <div className="hidden md:flex items-center gap-8">
          <Link
            to="/nosotros"
            className={`${navLink} ${pathname === '/nosotros' ? activeClass : inactiveClass}`}
          >
            Nosotros
          </Link>

          {/* Dropdown */}
          <div
            className="relative"
            onMouseEnter={() => setDropdownOpen(true)}
            onMouseLeave={() => setDropdownOpen(false)}
          >
            <button
              className={`${navLink} flex items-center gap-1 ${
                pathname.startsWith('/tarjetas') ||
                pathname === '/rollos-termicos' ||
                pathname === '/sobres-preimpresos' ||
                pathname === '/fundas-rfid'
                  ? activeClass
                  : inactiveClass
              }`}
            >
              Productos y Servicios
              <ChevronDown
                size={15}
                className={`transition-transform duration-200 ${dropdownOpen ? 'rotate-180' : ''}`}
              />
            </button>
            <AnimatePresence>
              {dropdownOpen && (
                <motion.div
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: 8 }}
                  transition={{ duration: 0.18 }}
                  className="absolute top-full left-1/2 -translate-x-1/2 mt-1 w-52 bg-white rounded-xl shadow-card-hover border border-gray-100 overflow-hidden"
                >
                  {products.map((p) => (
                    <Link
                      key={p.href}
                      to={p.href}
                      className={`block px-4 py-3 text-sm font-medium transition-colors ${
                        pathname === p.href
                          ? 'bg-blue-50 text-brand-blue'
                          : 'text-gray-700 hover:bg-gray-50 hover:text-brand-blue'
                      }`}
                    >
                      {p.label}
                    </Link>
                  ))}
                  <Link
                    to="/productos"
                    className="block px-4 py-3 text-sm font-semibold text-brand-navy border-t border-gray-100 hover:bg-navy-50 transition-colors"
                  >
                    Ver todos los productos →
                  </Link>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <Link
            to="/clientes"
            className={`${navLink} ${pathname === '/clientes' ? activeClass : inactiveClass}`}
          >
            Clientes
          </Link>
          <Link
            to="/blog"
            className={`${navLink} ${pathname.startsWith('/blog') ? activeClass : inactiveClass}`}
          >
            Blog
          </Link>
          <Link
            to="/contacto"
            className="px-5 py-2 bg-brand-navy text-white text-sm font-semibold rounded-lg hover:bg-navy-800 transition-colors duration-200"
          >
            Contacto
          </Link>
        </div>

        {/* Mobile toggle */}
        <button
          className="md:hidden p-2 rounded-lg text-gray-700 hover:bg-gray-100"
          onClick={() => setMobileOpen((v) => !v)}
          aria-label="Menú"
        >
          {mobileOpen ? <X size={22} /> : <Menu size={22} />}
        </button>
      </div>

      {/* Mobile menu */}
      <AnimatePresence>
        {mobileOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.22 }}
            className="md:hidden overflow-hidden border-t border-gray-100 bg-white"
          >
            <div className="px-4 py-4 flex flex-col gap-2">
              <Link
                to="/nosotros"
                className="py-2.5 text-sm font-medium text-gray-700 hover:text-brand-blue"
              >
                Nosotros
              </Link>
              <div className="py-1">
                <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">
                  Productos y Servicios
                </p>
                {products.map((p) => (
                  <Link
                    key={p.href}
                    to={p.href}
                    className="block py-2 pl-3 text-sm text-gray-700 hover:text-brand-blue border-l-2 border-gray-100 hover:border-brand-blue transition-colors"
                  >
                    {p.label}
                  </Link>
                ))}
                <Link
                  to="/productos"
                  className="block py-2 pl-3 text-sm font-semibold text-brand-navy border-l-2 border-brand-navy"
                >
                  Ver todos →
                </Link>
              </div>
              <Link
                to="/clientes"
                className="py-2.5 text-sm font-medium text-gray-700 hover:text-brand-blue"
              >
                Clientes
              </Link>
              <Link
                to="/blog"
                className="py-2.5 text-sm font-medium text-gray-700 hover:text-brand-blue"
              >
                Blog
              </Link>
              <Link
                to="/contacto"
                className="mt-2 py-3 text-center bg-brand-navy text-white text-sm font-semibold rounded-lg"
              >
                Contacto
              </Link>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </nav>
  )
}

// keysolutions/src/components/NavBar.vue
<template>
  <nav class="navbar navbar-expand-lg sticky-top">
    <div class="container-fluid">
      <router-link to="/" class="navbar-brand"><img src="../assets/logoKey.png" alt="Logo Key Solutions S.A.C" id="logoKey"></router-link>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <router-link to="/nosotros" class="nav-link"  @click="closeNavbar">Nosotros </router-link>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Productos y Servicios 
            </a>
            <ul class="dropdown-menu">
              <li><router-link to="/tarjetas-banca" class="dropdown-item" @click="closeNavbar">Tarjetas Banca</router-link></li>
              <li><router-link to="/tarjetas-empresa" class="dropdown-item"  @click="closeNavbar">Tarjetas Empresa</router-link></li>
              <li><router-link to="/rollos" class="dropdown-item"  @click="closeNavbar">Rollos Termicos</router-link></li>
              <li><router-link to="/sobres-preimpresos" class="dropdown-item"  @click="closeNavbar">Formularios y Sobres</router-link></li>
              <li><router-link to="/fundas-bloqueo" class="dropdown-item"  @click="closeNavbar">Fundas de Bloqueo RFID</router-link></li>
              <li><hr class="dropdown-divider"></li>
              <li><router-link to="/products" class="dropdown-item"  @click="closeNavbar">Todos los productos</router-link></li>
            </ul>
          </li>

          
          <li class="nav-item">
            <router-link to="/contact" class="nav-link"  @click="closeNavbar">Contacto</router-link>
          </li>
        </ul>
        <!-- <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Buscar</button>
        </form> -->
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'NavBar',
  methods: {
  closeNavbar() {
    const navbarToggler = this.$el.querySelector('.navbar-toggler');
    if (navbarToggler && !navbarToggler.classList.contains('collapsed')) {
      navbarToggler.click();
    }
  }
}
}
</script>

<style scoped>
/* Add your header styles here */
.navbar {
background-color: #fff;

}


.btn-outline-success{
  color: #fff;
  background-color: grey;
  border-color: grey;
  transition: 0.2s ease-out, border-color 0.2s ease-out;
}
.btn-outline-success:hover{
  background-color: grey;
  border-color: #fff;
  transition: 0.2s ease-out, border 0.2s ease-out;
  transform: scale(1.1);
}

.nav-item{
  color: black;
  transition: 0.2s ease-out, border 0.2s ease-out;
}
.nav-item:hover{
  color:rgb(101, 101, 101);
  transition: 0.2s ease-out, border 0.2s ease-out;
  transform: scale(1.1);
}

.nav-link {
  color: black;
  transition: color 0.2s ease-out, transform 0.2s ease-out;
}

.nav-link:hover {
  color: rgb(101, 101, 101);
  transform: scale(1.05);
}

.navbar-brand{
  color: black;
  
}

.dropdown-item{
  color: black;
}
.dropdown-item:hover{
  color: rgb(101, 101, 101);
  transform: scale(1.02);
  transition: transform 0.2s ease-out;
  background-color: transparent;

}


/* Set a minimum and maximum width for the images on small screens */

@media (max-width: 576px) {

  #logoKey{
    width: 200px;
    height: 60px;
  }
}



/* Set a minimum and maximum width for the images on medium screens */
@media (min-width: 576px) and (max-width: 768px) {
  #logoKey{
    width: 200px;
    height: 60px;
  }
}


/* Set a minimum and maximum width for the images on large screens */
@media (min-width: 768px) {
  #logoKey{
    width: 200px;
    height: 60px;
  }
}


</style>
