// src/pages/TarjetasEmpresa.jsx
import { Link } from 'react-router-dom'
import { ArrowRight } from 'lucide-react'
import { tarjetasEmpresa } from '../data/products'
import ProductCard from '../components/ui/ProductCard'
import ProductDetailHero from '../components/ui/ProductDetailHero'
import SectionTitle from '../components/ui/SectionTitle'
import AnimatedSection from '../components/ui/AnimatedSection'
import SEOHead from '../components/SEOHead'
import frenteReverso from '../assets/frente-reverso.avif'

const sectors = [
  'Hoteles y complejos hoteleros',
  'Casinos y entretenimiento',
  'Empresas de seguros',
  'Sistemas de transporte',
  'Instituciones educativas',
  'Corporaciones y empresas',
]

export default function TarjetasEmpresa() {
  return (
    <>
      <SEOHead
        title="Tarjetas PVC Empresa, Hotel y Control de Acceso | Key Solutions S.A.C"
        description="Tarjetas PVC para hoteles, casinos, corporaciones y sistemas de control de acceso. Chip, banda magnética y código de barras. Impresión personalizada. Perú y Bolivia."
        keywords="tarjetas PVC empresa, tarjetas hotel llave, tarjetas control acceso, tarjetas identificacion corporativa, tarjeta magnetica hotel, tarjetas PVC personalizadas, carnet corporativo, tarjeta casino, tarjeta acceso Peru Bolivia"
        path="/tarjetas-empresa"
      />

      <ProductDetailHero
        label="Tarjetas corporativas"
        title="Tarjetas Empresa"
        subtitle="Identificación · Control de acceso · Llaves de hotel — Soluciones PVC para el sector empresarial"
      />

      <section className="py-20 bg-brand-light">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">
          <SectionTitle
            label="Tipos disponibles"
            title="Tarjetas para cada necesidad empresarial"
          />
          <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 gap-6 max-w-3xl mx-auto">
            {tarjetasEmpresa.map((card, i) => (
              <ProductCard key={card.title} product={card} index={i} />
            ))}
          </div>
        </div>
      </section>

      {/* Sectors */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 grid grid-cols-1 lg:grid-cols-2 gap-14 items-center">
          <AnimatedSection direction="right" className="order-2 lg:order-1">
            <span className="text-xs font-semibold tracking-widest uppercase text-brand-blue">
              Sectores que atendemos
            </span>
            <h2 className="mt-2 text-3xl font-extrabold text-navy-900 mb-6">
              Diseñadas para su industria
            </h2>
            <ul className="space-y-3">
              {sectors.map((s) => (
                <li key={s} className="flex items-center gap-3 text-gray-700">
                  <span className="w-2 h-2 rounded-full bg-brand-gold flex-shrink-0" />
                  {s}
                </li>
              ))}
            </ul>
            <Link
              to="/contacto"
              className="inline-flex items-center gap-2 mt-8 px-7 py-3.5 bg-brand-navy text-white font-semibold rounded-xl hover:bg-navy-800 transition-colors"
            >
              Solicitar cotización
              <ArrowRight size={17} />
            </Link>
          </AnimatedSection>
          <AnimatedSection direction="left" className="order-1 lg:order-2">
            <img
              src={frenteReverso}
              alt="Tarjeta empresa"
              className="w-full max-w-md mx-auto rounded-2xl shadow-card-hover animate-float"
            />
          </AnimatedSection>
        </div>
      </section>
    </>
  )
}

// keysolutions/src/views/TarjetasEmpresa.vue
<template>
    <div class="ProductsView" >
      <h1>Key Solutions S.A.C</h1>

      <div class="row">
      <hr>

      <div class="col-md-6  mx-auto text-center">

        <h3 class="title">Tarjetas para Hoteles, Casinos, Seguros, Empresas, Calendarios y Más : </h3>

        
        <div class="blue-background" >
          <span class="description d-block">La versatilidad de nuestro producto permite diseños a la medida de los requerimientos de nuestros clientes, con la posibilidad de incluir tecnología de banda magnética, chip, código de barras, impresión de datos variables, entre otros.
          <br><br>
          Trabajamos con todo tipo de modelos para tarjetas.
          </span>
        </div>
        
      </div>
      <div class="col-md-5">
        <img src="../assets/tarjeta-pvc-hotel.png" class="img-fluid" alt="Amberso y reverso tarjeta débito">
      </div>
      <div class="text-center">
        <router-link to="/contact" class="btn rounded-pill contact-btn">
          Solicitar Cotización y/o Consultas 
        </router-link>
      </div>
      <hr>
    </div>
      <h2>Tarjetas Empresa:</h2>
      <br>
      <tarjetas :data="tarjetasempresa" />
    </div>
  </template>
  
  <script>
  import Tarjetas from '@/components/TarjetasComponent.vue'
  
  export default {
    name: 'TarjetaEmpresa',
    components: {
      Tarjetas
    },
    data() {
      return {
        tarjetasempresa: [
        {
          title: 'Tarjeta Identificación / Control de Acceso',
          description: 'Chip | Banda Magnetica',
          image: require('@/assets/tarjeta-identificacion.avif')
        },
        {
          title: 'Tarjeta para Hoteles',
          description: 'Chip | Banda Magnetica',
          image: require('@/assets/tarjeta-hotel.avif')
        },
        ]
      }
    }
  }
  </script>


<style scoped> 
.blue-background {
  background-color: #f0f8ff;

  
}

.description {
  padding: 20px;
  border-radius: 10px;
  font-size: 1.5em;
  margin-bottom: 20px;
  font-weight: normal;
}

.contact-btn{
  margin-top: 20px;
  margin-bottom: 20px;
  font-size: 1.6rem;
  background-color: #0c3e6b;
  color: white;
  letter-spacing: 1px;
}

.title{
  font-size: 2em;
  margin-top: 20px;
  margin-bottom: 20px;
}
</style>
